apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/services.yaml
  - apps/ingress.yaml
  - infrastructure/mongodb.yaml
  - infrastructure/postgres.yaml
  - secret.yaml

configMapGenerator:
  - name: rocket-factory-config
