---
apiVersion: v1
kind: Secret
metadata:
  name: rocket-factory-secrets
type: Opaque
stringData:
  ORDER_DB_USER: order-service-user
  ORDER_DB_PASSWORD: order-service-password
  INVENTORY_DB_USER: inventory-service-user
  INVENTORY_DB_PASSWORD: inventory-service-password
...
