# template: testify
dir: "{{.InterfaceDir}}/mock"
filename: "mock_{{.InterfaceName | snakecase}}.go"
pkgname: "mock"
structname: "{{.InterfaceName}}"

packages:
    github.com/ekuzm/rocket-factory/inventory/internal/api/v1:
        config:
            include-interface-regex: ".*Service"
    github.com/ekuzm/rocket-factory/inventory/internal/service:
        config:
            include-interface-regex: ".*Repository || .*Port"
    github.com/ekuzm/rocket-factory/order/internal/api/v1:
        config:
            include-interface-regex: ".*Service"
    github.com/ekuzm/rocket-factory/order/internal/service:
        config:
            include-interface-regex: ".*Repository || .*Port"
    github.com/ekuzm/rocket-factory/payment/internal/api/v1:
        config:
            include-interface-regex: ".*Service"
    github.com/ekuzm/rocket-factory/payment/internal/service:
        config:
            include-interface-regex: ".*Repository || .*Port"
