// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/ekuzm/rocket-factory/inventory/internal/dto"
)

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

type InventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryService) EXPECT() *InventoryService_Expecter {
	return &InventoryService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type InventoryService
func (_mock *InventoryService) GetPart(ctx context.Context, input dto.GetPartInput) (dto.GetPartOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 dto.GetPartOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetPartInput) (dto.GetPartOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetPartInput) dto.GetPartOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(dto.GetPartOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetPartInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.GetPartInput
func (_e *InventoryService_Expecter) GetPart(ctx, input interface{}) *InventoryService_GetPart_Call {
	return &InventoryService_GetPart_Call{Call: _e.mock.On("GetPart", ctx, input)}
}

func (_c *InventoryService_GetPart_Call) Run(run func(ctx context.Context, input dto.GetPartInput)) *InventoryService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetPartInput
		if args[1] != nil {
			arg1 = args[1].(dto.GetPartInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryService_GetPart_Call) Return(getPartOutput dto.GetPartOutput, err error) *InventoryService_GetPart_Call {
	_c.Call.Return(getPartOutput, err)
	return _c
}

func (_c *InventoryService_GetPart_Call) RunAndReturn(run func(ctx context.Context, input dto.GetPartInput) (dto.GetPartOutput, error)) *InventoryService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type InventoryService
func (_mock *InventoryService) ListParts(ctx context.Context, input dto.ListPartsInput) (dto.ListPartsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 dto.ListPartsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListPartsInput) (dto.ListPartsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListPartsInput) dto.ListPartsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(dto.ListPartsOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ListPartsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.ListPartsInput
func (_e *InventoryService_Expecter) ListParts(ctx, input interface{}) *InventoryService_ListParts_Call {
	return &InventoryService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, input)}
}

func (_c *InventoryService_ListParts_Call) Run(run func(ctx context.Context, input dto.ListPartsInput)) *InventoryService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ListPartsInput
		if args[1] != nil {
			arg1 = args[1].(dto.ListPartsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryService_ListParts_Call) Return(listPartsOutput dto.ListPartsOutput, err error) *InventoryService_ListParts_Call {
	_c.Call.Return(listPartsOutput, err)
	return _c
}

func (_c *InventoryService_ListParts_Call) RunAndReturn(run func(ctx context.Context, input dto.ListPartsInput) (dto.ListPartsOutput, error)) *InventoryService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
