// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	model0 "github.com/ekuzm/rocket-factory/order/internal/model"
	"github.com/ekuzm/rocket-factory/order/internal/repository/model"
)

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) CancelOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderRepository_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) CancelOrder(ctx, order interface{}) *OrderRepository_CancelOrder_Call {
	return &OrderRepository_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, order)}
}

func (_c *OrderRepository_CancelOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrderRepository_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_CancelOrder_Call) Return(err error) *OrderRepository_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *OrderRepository_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) GetOrder(ctx context.Context, uuid string) (model0.Order, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model0.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model0.Order, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model0.Order); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model0.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) GetOrder(ctx, uuid interface{}) *OrderRepository_GetOrder_Call {
	return &OrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, uuid)}
}

func (_c *OrderRepository_GetOrder_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_GetOrder_Call) Return(order model0.Order, err error) *OrderRepository_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_GetOrder_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model0.Order, error)) *OrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) PayOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderRepository_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) PayOrder(ctx, order interface{}) *OrderRepository_PayOrder_Call {
	return &OrderRepository_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, order)}
}

func (_c *OrderRepository_PayOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrderRepository_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_PayOrder_Call) Return(err error) *OrderRepository_PayOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_PayOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *OrderRepository_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) SaveOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type OrderRepository_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) SaveOrder(ctx, order interface{}) *OrderRepository_SaveOrder_Call {
	return &OrderRepository_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order)}
}

func (_c *OrderRepository_SaveOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrderRepository_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_SaveOrder_Call) Return(err error) *OrderRepository_SaveOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_SaveOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *OrderRepository_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}
