// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/ekuzm/rocket-factory/order/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) GetOrder(ctx context.Context, uuid1 uuid.UUID) (model.Order, error) {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(ctx, uuid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *OrderRepository_Expecter) GetOrder(ctx interface{}, uuid1 interface{}) *OrderRepository_GetOrder_Call {
	return &OrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, uuid1)}
}

func (_c *OrderRepository_GetOrder_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *OrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_GetOrder_Call) Return(order model.Order, err error) *OrderRepository_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_GetOrder_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) (model.Order, error)) *OrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) SaveOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type OrderRepository_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) SaveOrder(ctx interface{}, order interface{}) *OrderRepository_SaveOrder_Call {
	return &OrderRepository_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order)}
}

func (_c *OrderRepository_SaveOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrderRepository_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_SaveOrder_Call) Return(err error) *OrderRepository_SaveOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_SaveOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *OrderRepository_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) UpdateOrder(ctx context.Context, uuid1 uuid.UUID, info model.OrderInfo) error {
	ret := _mock.Called(ctx, uuid1, info)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.OrderInfo) error); ok {
		r0 = returnFunc(ctx, uuid1, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
//   - info model.OrderInfo
func (_e *OrderRepository_Expecter) UpdateOrder(ctx interface{}, uuid1 interface{}, info interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, uuid1, info)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID, info model.OrderInfo)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.OrderInfo
		if args[2] != nil {
			arg2 = args[2].(model.OrderInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return(err error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID, info model.OrderInfo) error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}
