// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/ekuzm/rocket-factory/order/internal/dto"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type OrderService
func (_mock *OrderService) CancelOrder(ctx context.Context, input dto.CancelOrderInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CancelOrderInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CancelOrderInput
func (_e *OrderService_Expecter) CancelOrder(ctx, input interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, input)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, input dto.CancelOrderInput)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CancelOrderInput
		if args[1] != nil {
			arg1 = args[1].(dto.CancelOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(err error) *OrderService_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, input dto.CancelOrderInput) error) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type OrderService
func (_mock *OrderService) CreateOrder(ctx context.Context, input dto.CreateOrderInput) (dto.CreateOrderOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 dto.CreateOrderOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateOrderInput) (dto.CreateOrderOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateOrderInput) dto.CreateOrderOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(dto.CreateOrderOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateOrderInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CreateOrderInput
func (_e *OrderService_Expecter) CreateOrder(ctx, input interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, input)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, input dto.CreateOrderInput)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateOrderInput
		if args[1] != nil {
			arg1 = args[1].(dto.CreateOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(createOrderOutput dto.CreateOrderOutput, err error) *OrderService_CreateOrder_Call {
	_c.Call.Return(createOrderOutput, err)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, input dto.CreateOrderInput) (dto.CreateOrderOutput, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type OrderService
func (_mock *OrderService) GetOrder(ctx context.Context, input dto.GetOrderInput) (dto.GetOrderOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 dto.GetOrderOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetOrderInput) (dto.GetOrderOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetOrderInput) dto.GetOrderOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(dto.GetOrderOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetOrderInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.GetOrderInput
func (_e *OrderService_Expecter) GetOrder(ctx, input interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, input)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, input dto.GetOrderInput)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetOrderInput
		if args[1] != nil {
			arg1 = args[1].(dto.GetOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(getOrderOutput dto.GetOrderOutput, err error) *OrderService_GetOrder_Call {
	_c.Call.Return(getOrderOutput, err)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, input dto.GetOrderInput) (dto.GetOrderOutput, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type OrderService
func (_mock *OrderService) PayOrder(ctx context.Context, input dto.PayOrderInput) (dto.PayOrderOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 dto.PayOrderOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PayOrderInput) (dto.PayOrderOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PayOrderInput) dto.PayOrderOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(dto.PayOrderOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.PayOrderInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.PayOrderInput
func (_e *OrderService_Expecter) PayOrder(ctx, input interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, input)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, input dto.PayOrderInput)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.PayOrderInput
		if args[1] != nil {
			arg1 = args[1].(dto.PayOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(payOrderOutput dto.PayOrderOutput, err error) *OrderService_PayOrder_Call {
	_c.Call.Return(payOrderOutput, err)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, input dto.PayOrderInput) (dto.PayOrderOutput, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
