// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTransactionManager creates a new instance of TransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
},
) *TransactionManager {
	mock := &TransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionManager is an autogenerated mock type for the TransactionManager type
type TransactionManager struct {
	mock.Mock
}

type TransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionManager) EXPECT() *TransactionManager_Expecter {
	return &TransactionManager_Expecter{mock: &_m.Mock}
}

// Wrap provides a mock function for the type TransactionManager
func (_mock *TransactionManager) Wrap(context1 context.Context, fn func(context.Context) error) error {
	ret := _mock.Called(context1, fn)

	if len(ret) == 0 {
		panic("no return value specified for Wrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = returnFunc(context1, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionManager_Wrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wrap'
type TransactionManager_Wrap_Call struct {
	*mock.Call
}

// Wrap is a helper method to define mock.On call
//   - context1 context.Context
//   - fn func(context.Context) error
func (_e *TransactionManager_Expecter) Wrap(context1, fn interface{}) *TransactionManager_Wrap_Call {
	return &TransactionManager_Wrap_Call{Call: _e.mock.On("Wrap", context1, fn)}
}

func (_c *TransactionManager_Wrap_Call) Run(run func(context1 context.Context, fn func(context.Context) error)) *TransactionManager_Wrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionManager_Wrap_Call) Return(err error) *TransactionManager_Wrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionManager_Wrap_Call) RunAndReturn(run func(context1 context.Context, fn func(context.Context) error) error) *TransactionManager_Wrap_Call {
	_c.Call.Return(run)
	return _c
}
