// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/ekuzm/rocket-factory/order/internal/model/supplier"
)

// NewInventoryPort creates a new instance of InventoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryPort(t interface {
	mock.TestingT
	Cleanup(func())
},
) *InventoryPort {
	mock := &InventoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryPort is an autogenerated mock type for the InventoryPort type
type InventoryPort struct {
	mock.Mock
}

type InventoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryPort) EXPECT() *InventoryPort_Expecter {
	return &InventoryPort_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function for the type InventoryPort
func (_mock *InventoryPort) ListParts(ctx context.Context, filter supplier.Filter) ([]supplier.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []supplier.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, supplier.Filter) ([]supplier.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, supplier.Filter) []supplier.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]supplier.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, supplier.Filter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryPort_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryPort_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter supplier.Filter
func (_e *InventoryPort_Expecter) ListParts(ctx, filter interface{}) *InventoryPort_ListParts_Call {
	return &InventoryPort_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *InventoryPort_ListParts_Call) Run(run func(ctx context.Context, filter supplier.Filter)) *InventoryPort_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 supplier.Filter
		if args[1] != nil {
			arg1 = args[1].(supplier.Filter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryPort_ListParts_Call) Return(parts []supplier.Part, err error) *InventoryPort_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *InventoryPort_ListParts_Call) RunAndReturn(run func(ctx context.Context, filter supplier.Filter) ([]supplier.Part, error)) *InventoryPort_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
