// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

package inventory_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryV1Service_GetPart_FullMethodName   = "/inventory.v1.InventoryV1Service/GetPart"
	InventoryV1Service_ListParts_FullMethodName = "/inventory.v1.InventoryV1Service/ListParts"
)

// InventoryV1ServiceClient is the client API for InventoryV1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryV1ServiceClient interface {
	GetPart(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error)
	ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (*ListPartsResponse, error)
}

type inventoryV1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryV1ServiceClient(cc grpc.ClientConnInterface) InventoryV1ServiceClient {
	return &inventoryV1ServiceClient{cc}
}

func (c *inventoryV1ServiceClient) GetPart(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartResponse)
	err := c.cc.Invoke(ctx, InventoryV1Service_GetPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryV1ServiceClient) ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (*ListPartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartsResponse)
	err := c.cc.Invoke(ctx, InventoryV1Service_ListParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryV1ServiceServer is the server API for InventoryV1Service service.
// All implementations must embed UnimplementedInventoryV1ServiceServer
// for forward compatibility.
type InventoryV1ServiceServer interface {
	GetPart(context.Context, *GetPartRequest) (*GetPartResponse, error)
	ListParts(context.Context, *ListPartsRequest) (*ListPartsResponse, error)
	mustEmbedUnimplementedInventoryV1ServiceServer()
}

// UnimplementedInventoryV1ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryV1ServiceServer struct{}

func (UnimplementedInventoryV1ServiceServer) GetPart(context.Context, *GetPartRequest) (*GetPartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPart not implemented")
}
func (UnimplementedInventoryV1ServiceServer) ListParts(context.Context, *ListPartsRequest) (*ListPartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParts not implemented")
}
func (UnimplementedInventoryV1ServiceServer) mustEmbedUnimplementedInventoryV1ServiceServer() {}
func (UnimplementedInventoryV1ServiceServer) testEmbeddedByValue()                            {}

// UnsafeInventoryV1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryV1ServiceServer will
// result in compilation errors.
type UnsafeInventoryV1ServiceServer interface {
	mustEmbedUnimplementedInventoryV1ServiceServer()
}

func RegisterInventoryV1ServiceServer(s grpc.ServiceRegistrar, srv InventoryV1ServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryV1ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryV1Service_ServiceDesc, srv)
}

func _InventoryV1Service_GetPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryV1ServiceServer).GetPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryV1Service_GetPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryV1ServiceServer).GetPart(ctx, req.(*GetPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryV1Service_ListParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryV1ServiceServer).ListParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryV1Service_ListParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryV1ServiceServer).ListParts(ctx, req.(*ListPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryV1Service_ServiceDesc is the grpc.ServiceDesc for InventoryV1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryV1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryV1Service",
	HandlerType: (*InventoryV1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPart",
			Handler:    _InventoryV1Service_GetPart_Handler,
		},
		{
			MethodName: "ListParts",
			Handler:    _InventoryV1Service_ListParts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
