// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/ekuzm/rocket-factory/order/internal/model"
	"github.com/ekuzm/rocket-factory/order/internal/service/order/dto"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type OrderService
func (_mock *OrderService) CancelOrder(ctx context.Context, uuid1 uuid.UUID) error {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *OrderService_Expecter) CancelOrder(ctx, uuid1 interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, uuid1)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(err error) *OrderService_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) error) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type OrderService
func (_mock *OrderService) CreateOrder(ctx context.Context, userUUID uuid.UUID, partUUIDs uuid.UUIDs) (dto.Summary, error) {
	ret := _mock.Called(ctx, userUUID, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 dto.Summary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUIDs) (dto.Summary, error)); ok {
		return returnFunc(ctx, userUUID, partUUIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUIDs) dto.Summary); ok {
		r0 = returnFunc(ctx, userUUID, partUUIDs)
	} else {
		r0 = ret.Get(0).(dto.Summary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUIDs) error); ok {
		r1 = returnFunc(ctx, userUUID, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - partUUIDs uuid.UUIDs
func (_e *OrderService_Expecter) CreateOrder(ctx, userUUID, partUUIDs interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userUUID, partUUIDs)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, partUUIDs uuid.UUIDs)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUIDs
		if args[2] != nil {
			arg2 = args[2].(uuid.UUIDs)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(summary dto.Summary, err error) *OrderService_CreateOrder_Call {
	_c.Call.Return(summary, err)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID, partUUIDs uuid.UUIDs) (dto.Summary, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type OrderService
func (_mock *OrderService) GetOrder(ctx context.Context, uuid1 uuid.UUID) (model.Order, error) {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(ctx, uuid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *OrderService_Expecter) GetOrder(ctx, uuid1 interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, uuid1)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(order model.Order, err error) *OrderService_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) (model.Order, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type OrderService
func (_mock *OrderService) PayOrder(ctx context.Context, uuid1 uuid.UUID, paymentMethod model.PaymentMethod) (uuid.UUID, error) {
	ret := _mock.Called(ctx, uuid1, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)); ok {
		return returnFunc(ctx, uuid1, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod) uuid.UUID); ok {
		r0 = returnFunc(ctx, uuid1, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, uuid1, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
//   - paymentMethod model.PaymentMethod
func (_e *OrderService_Expecter) PayOrder(ctx, uuid1, paymentMethod interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, uuid1, paymentMethod)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID, paymentMethod model.PaymentMethod)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(model.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(uUID uuid.UUID, err error) *OrderService_PayOrder_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID, paymentMethod model.PaymentMethod) (uuid.UUID, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
