// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: payment/v1/payment.proto

package payment_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentV1Service_PayOrder_FullMethodName = "/payment.v1.PaymentV1Service/PayOrder"
)

// PaymentV1ServiceClient is the client API for PaymentV1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentV1ServiceClient interface {
	PayOrder(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error)
}

type paymentV1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentV1ServiceClient(cc grpc.ClientConnInterface) PaymentV1ServiceClient {
	return &paymentV1ServiceClient{cc}
}

func (c *paymentV1ServiceClient) PayOrder(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayOrderResponse)
	err := c.cc.Invoke(ctx, PaymentV1Service_PayOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentV1ServiceServer is the server API for PaymentV1Service service.
// All implementations must embed UnimplementedPaymentV1ServiceServer
// for forward compatibility.
type PaymentV1ServiceServer interface {
	PayOrder(context.Context, *PayOrderRequest) (*PayOrderResponse, error)
	mustEmbedUnimplementedPaymentV1ServiceServer()
}

// UnimplementedPaymentV1ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentV1ServiceServer struct{}

func (UnimplementedPaymentV1ServiceServer) PayOrder(context.Context, *PayOrderRequest) (*PayOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayOrder not implemented")
}
func (UnimplementedPaymentV1ServiceServer) mustEmbedUnimplementedPaymentV1ServiceServer() {}
func (UnimplementedPaymentV1ServiceServer) testEmbeddedByValue()                          {}

// UnsafePaymentV1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentV1ServiceServer will
// result in compilation errors.
type UnsafePaymentV1ServiceServer interface {
	mustEmbedUnimplementedPaymentV1ServiceServer()
}

func RegisterPaymentV1ServiceServer(s grpc.ServiceRegistrar, srv PaymentV1ServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentV1ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentV1Service_ServiceDesc, srv)
}

func _PaymentV1Service_PayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentV1ServiceServer).PayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentV1Service_PayOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentV1ServiceServer).PayOrder(ctx, req.(*PayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentV1Service_ServiceDesc is the grpc.ServiceDesc for PaymentV1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentV1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentV1Service",
	HandlerType: (*PaymentV1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayOrder",
			Handler:    _PaymentV1Service_PayOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/v1/payment.proto",
}
