// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/ekuzm/rocket-factory/payment/internal/dto"
)

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

type PaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentService) EXPECT() *PaymentService_Expecter {
	return &PaymentService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type PaymentService
func (_mock *PaymentService) PayOrder(ctx context.Context, input dto.PayOrderInput) (dto.PayOrderOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 dto.PayOrderOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PayOrderInput) (dto.PayOrderOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PayOrderInput) dto.PayOrderOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(dto.PayOrderOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.PayOrderInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.PayOrderInput
func (_e *PaymentService_Expecter) PayOrder(ctx, input interface{}) *PaymentService_PayOrder_Call {
	return &PaymentService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, input)}
}

func (_c *PaymentService_PayOrder_Call) Run(run func(ctx context.Context, input dto.PayOrderInput)) *PaymentService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.PayOrderInput
		if args[1] != nil {
			arg1 = args[1].(dto.PayOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentService_PayOrder_Call) Return(payOrderOutput dto.PayOrderOutput, err error) *PaymentService_PayOrder_Call {
	_c.Call.Return(payOrderOutput, err)
	return _c
}

func (_c *PaymentService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, input dto.PayOrderInput) (dto.PayOrderOutput, error)) *PaymentService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
