// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/ekuzm/rocket-factory/order/internal/model"
)

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type PaymentClient
func (_mock *PaymentClient) PayOrder(ctx context.Context, payment model.Payment) (string, error) {
	ret := _mock.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Payment) (string, error)); ok {
		return returnFunc(ctx, payment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Payment) string); ok {
		r0 = returnFunc(ctx, payment)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Payment) error); ok {
		r1 = returnFunc(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - payment model.Payment
func (_e *PaymentClient_Expecter) PayOrder(ctx, payment interface{}) *PaymentClient_PayOrder_Call {
	return &PaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, payment)}
}

func (_c *PaymentClient_PayOrder_Call) Run(run func(ctx context.Context, payment model.Payment)) *PaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Payment
		if args[1] != nil {
			arg1 = args[1].(model.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentClient_PayOrder_Call) Return(s string, err error) *PaymentClient_PayOrder_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PaymentClient_PayOrder_Call) RunAndReturn(run func(ctx context.Context, payment model.Payment) (string, error)) *PaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
