// Code generated by ogen, DO NOT EDIT.

package order_v1

// setDefaults set default value of fields.
func (s *GetOrderResponse) setDefaults() {
	{
		val := GetOrderResponsePaymentMethod("UNKNOWN")
		s.PaymentMethod = val
	}
	{
		val := GetOrderResponseStatus("PENDING_PAYMENT")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *PayOrderRequest) setDefaults() {
	{
		val := PayOrderRequestPaymentMethod("UNKNOWN")
		s.PaymentMethod = val
	}
}
