// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements CancelOrder operation.
//
// Canceled order.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r *NoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements CreateOrder operation.
//
// Create a new order based on the parts selected by the user.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r *CreateOrderResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements GetOrder operation.
//
// Returns information about the order.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r *Order, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Performs payment for a previously created order.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r *PayOrderResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
