// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Canceled order.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (*NoContent, error)
	// CreateOrder implements CreateOrder operation.
	//
	// Create a new order based on the parts selected by the user.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error)
	// GetOrder implements GetOrder operation.
	//
	// Returns information about the order.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrder(ctx context.Context, params GetOrderParams) (*Order, error)
	// PayOrder implements PayOrder operation.
	//
	// Performs payment for a previously created order.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (*PayOrderResponse, error)
	// Ping implements Ping operation.
	//
	// Health check.
	//
	// GET /api/v1/ping
	Ping(ctx context.Context) error
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
