// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #
type BadRequestError struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) cancelOrderRes()    {}
func (*BadRequestError) createOrderRes()    {}
func (*BadRequestError) getOrderByUUIDRes() {}
func (*BadRequestError) payOrderRes()       {}

// Ref: #
type CreateOrderRequest struct {
	// User UUID.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Part UUIDs.
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #
type CreateOrderResponse struct {
	// Order UUID.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Total price for order.
	TotalPrice float64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #
type GenericError struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #
type InternalServerError struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) cancelOrderRes()    {}
func (*InternalServerError) createOrderRes()    {}
func (*InternalServerError) getOrderByUUIDRes() {}
func (*InternalServerError) payOrderRes()       {}

// Ref: #
type NoContentError struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NoContentError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NoContentError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NoContentError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NoContentError) SetMessage(val string) {
	s.Message = val
}

func (*NoContentError) cancelOrderRes() {}

// Ref: #
type NotFoundError struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderRes()    {}
func (*NotFoundError) createOrderRes()    {}
func (*NotFoundError) getOrderByUUIDRes() {}
func (*NotFoundError) payOrderRes()       {}

// Ref: #
type Order struct {
	// Order UUID.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// User UUID.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Part UUIDs.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Total price for order.
	TotalPrice float32 `json:"total_price"`
	// Transaction UUID.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
	// Payment method.
	PaymentMethod OrderPaymentMethod `json:"payment_method"`
	// Status of order.
	Status OrderStatus `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *Order) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *Order) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *Order) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *Order) GetTotalPrice() float32 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *Order) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Order) GetPaymentMethod() OrderPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *Order) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *Order) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *Order) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *Order) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *Order) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Order) SetPaymentMethod(val OrderPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*Order) getOrderByUUIDRes() {}

// Payment method.
type OrderPaymentMethod string

const (
	OrderPaymentMethodUNKNOWN       OrderPaymentMethod = "UNKNOWN"
	OrderPaymentMethodCARD          OrderPaymentMethod = "CARD"
	OrderPaymentMethodSBP           OrderPaymentMethod = "SBP"
	OrderPaymentMethodCREDITCARD    OrderPaymentMethod = "CREDIT_CARD"
	OrderPaymentMethodINVESTORMONEY OrderPaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all OrderPaymentMethod values.
func (OrderPaymentMethod) AllValues() []OrderPaymentMethod {
	return []OrderPaymentMethod{
		OrderPaymentMethodUNKNOWN,
		OrderPaymentMethodCARD,
		OrderPaymentMethodSBP,
		OrderPaymentMethodCREDITCARD,
		OrderPaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case OrderPaymentMethodUNKNOWN:
		return []byte(s), nil
	case OrderPaymentMethodCARD:
		return []byte(s), nil
	case OrderPaymentMethodSBP:
		return []byte(s), nil
	case OrderPaymentMethodCREDITCARD:
		return []byte(s), nil
	case OrderPaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderPaymentMethod) UnmarshalText(data []byte) error {
	switch OrderPaymentMethod(data) {
	case OrderPaymentMethodUNKNOWN:
		*s = OrderPaymentMethodUNKNOWN
		return nil
	case OrderPaymentMethodCARD:
		*s = OrderPaymentMethodCARD
		return nil
	case OrderPaymentMethodSBP:
		*s = OrderPaymentMethodSBP
		return nil
	case OrderPaymentMethodCREDITCARD:
		*s = OrderPaymentMethodCREDITCARD
		return nil
	case OrderPaymentMethodINVESTORMONEY:
		*s = OrderPaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Status of order.
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELED       OrderStatus = "CANCELED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELED:
		*s = OrderStatusCANCELED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #
type PayOrderRequest struct {
	// Payment method.
	PaymentMethod PayOrderRequestPaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PayOrderRequestPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PayOrderRequestPaymentMethod) {
	s.PaymentMethod = val
}

// Payment method.
type PayOrderRequestPaymentMethod string

const (
	PayOrderRequestPaymentMethodUNKNOWN       PayOrderRequestPaymentMethod = "UNKNOWN"
	PayOrderRequestPaymentMethodCARD          PayOrderRequestPaymentMethod = "CARD"
	PayOrderRequestPaymentMethodSBP           PayOrderRequestPaymentMethod = "SBP"
	PayOrderRequestPaymentMethodCREDITCARD    PayOrderRequestPaymentMethod = "CREDIT_CARD"
	PayOrderRequestPaymentMethodINVESTORMONEY PayOrderRequestPaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PayOrderRequestPaymentMethod values.
func (PayOrderRequestPaymentMethod) AllValues() []PayOrderRequestPaymentMethod {
	return []PayOrderRequestPaymentMethod{
		PayOrderRequestPaymentMethodUNKNOWN,
		PayOrderRequestPaymentMethodCARD,
		PayOrderRequestPaymentMethodSBP,
		PayOrderRequestPaymentMethodCREDITCARD,
		PayOrderRequestPaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PayOrderRequestPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PayOrderRequestPaymentMethodUNKNOWN:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodCARD:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodSBP:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodCREDITCARD:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PayOrderRequestPaymentMethod) UnmarshalText(data []byte) error {
	switch PayOrderRequestPaymentMethod(data) {
	case PayOrderRequestPaymentMethodUNKNOWN:
		*s = PayOrderRequestPaymentMethodUNKNOWN
		return nil
	case PayOrderRequestPaymentMethodCARD:
		*s = PayOrderRequestPaymentMethodCARD
		return nil
	case PayOrderRequestPaymentMethodSBP:
		*s = PayOrderRequestPaymentMethodSBP
		return nil
	case PayOrderRequestPaymentMethodCREDITCARD:
		*s = PayOrderRequestPaymentMethodCREDITCARD
		return nil
	case PayOrderRequestPaymentMethodINVESTORMONEY:
		*s = PayOrderRequestPaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #
type PayOrderResponse struct {
	// Transaction UUID.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}
