services:
  payment-service:
    container_name: payment-service
    env_file: ../../env/payment/.env
    build:
      context: ../../..
      dockerfile: ./deploy/docker/payment/Dockerfile
    ports:
      - 50052:50052
    healthcheck:
      test:
        - CMD
        - /app/grpc_health_probe
        - -addr=:${SERVICE_PORT}
        - -service=inventory.PaymentService
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - rocket-factory-net

networks:
  rocket-factory-net:
    external: true
